# Generated by Django 2.1.5 on 2020-12-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='upvotes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
