# Generated by Django 2.1.5 on 2020-12-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_answers_upvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Stud_Ans',
        ),
    ]
