# Generated by Django 2.1.5 on 2020-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201206_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_ans',
            name='answer',
            field=models.CharField(max_length=400),
        ),
    ]
