# Generated by Django 2.1.5 on 2020-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201206_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_ans',
            old_name='upvotes',
            new_name='total_upvotes',
        ),
        migrations.AddField(
            model_name='stud_ans',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
