# Generated by Django 2.1.5 on 2020-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201206_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_ans',
            name='upvote',
            field=models.BooleanField(null=True),
        ),
    ]
