# Generated by Django 2.1.5 on 2020-12-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi_student', '0002_auto_20201205_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='email_id',
        ),
    ]
