# Generated by Django 2.1.5 on 2020-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_student', '0003_auto_20201205_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
